using System.Windows;

namespace BackgroundAutomationStudio.Services;

public static class LocalizationService
{
    private static string _language = "en";
    public static string Language => _language;
    public static event EventHandler? LanguageChanged;

    private static readonly Dictionary<string, (string En, string Vi)> Text = new()
    {
        ["MenuFile"] = ("File", "Tệp"), ["MenuEdit"] = ("Edit", "Chỉnh sửa"), ["MenuHotkey"] = ("Hotkey", "Phím tắt"), ["MenuSettings"] = ("Settings", "Cài đặt"), ["RunStopShort"] = ("Run/Stop", "Chạy/Dừng"), ["PauseShort"] = ("Pause", "Tạm dừng"),
        ["NewProject"] = ("New project", "Dự án mới"), ["Open"] = ("Open...", "Mở..."), ["Save"] = ("Save", "Lưu"), ["SaveAs"] = ("Save as...", "Lưu thành..."),
        ["EditAction"] = ("Edit action", "Sửa thao tác"), ["DuplicateAction"] = ("Duplicate action", "Nhân bản thao tác"), ["DeleteAction"] = ("Delete action", "Xóa thao tác"), ["CopyAction"] = ("Copy action", "Sao chép thao tác"), ["CutAction"] = ("Cut action", "Cắt thao tác"), ["PasteAction"] = ("Paste action", "Dán thao tác"), ["ToggleSkip"] = ("Skip / enable action", "Bỏ qua / bật thao tác"), ["Undo"] = ("Undo", "Hoàn tác"), ["Redo"] = ("Redo", "Làm lại"), ["MoveUp"] = ("Move up", "Di chuyển lên"), ["MoveDown"] = ("Move down", "Di chuyển xuống"),
        ["VersionLabel"] = ("Version 2.3.3 - Reliable Foreground Game Input", "Phiên bản 2.3.3 - Input game phía trước tin cậy"),
        ["PinWindow"] = ("Keep window on top", "Ghim cửa sổ lên trên"), ["UnpinWindow"] = ("Stop keeping window on top", "Bỏ ghim cửa sổ"), ["MinimizeWindow"] = ("Minimize", "Thu nhỏ"), ["MaximizeWindow"] = ("Maximize", "Phóng to"), ["RestoreWindow"] = ("Restore", "Khôi phục"), ["CloseWindow"] = ("Close", "Đóng"),
        ["TargetWindow"] = ("Target window", "Cửa sổ đích"), ["ClientCoordinates"] = ("CLIENT COORDINATES", "TỌA ĐỘ VÙNG KHÁCH"), ["TargetHelp"] = ("Choose the exact window that receives recorded and replayed actions.", "Chọn đúng cửa sổ sẽ nhận thao tác ghi và phát lại."), ["SelectWindow"] = ("Select window", "Chọn cửa sổ"),
        ["Application"] = ("APPLICATION", "ỨNG DỤNG"), ["WindowTitle"] = ("WINDOW TITLE", "TIÊU ĐỀ CỬA SỔ"), ["Class"] = ("CLASS", "LỚP"), ["NotSelected"] = ("Not selected", "Chưa chọn"), ["NotCaptured"] = ("Not captured", "Chưa ghi nhận"), ["RecordedLayout"] = ("RECORDED WINDOW LAYOUT", "BỐ CỤC CỬA SỔ ĐÃ GHI"),
        ["CapturePlayback"] = ("Capture & playback", "Ghi & phát lại"), ["Recording"] = ("RECORDING", "ĐANG GHI"), ["Record"] = ("Record", "Ghi"), ["StopRecord"] = ("Stop record", "Dừng ghi"), ["CancelRecord"] = ("Cancel record", "Hủy ghi"), ["RunWorkflow"] = ("Run workflow", "Chạy quy trình"), ["Pause"] = ("Pause", "Tạm dừng"), ["Resume"] = ("Resume", "Tiếp tục"), ["StopRun"] = ("Stop run", "Dừng chạy"),
        ["RepeatMode"] = ("RUN SCHEDULE", "LỊCH CHẠY"), ["RepeatCount"] = ("REPEAT COUNT", "SỐ LẦN LẶP"), ["RepeatHelp"] = ("Choose a count, run forever, run for a duration, or stop at a clock time.", "Chọn số lần, chạy vô tận, chạy theo thời lượng hoặc dừng tại một giờ cụ thể."),
        ["RepeatCountMode"] = ("Repeat a set number", "Lặp theo số lần"), ["RepeatInfiniteMode"] = ("Run until stopped", "Chạy vô tận đến khi dừng"), ["RepeatDurationMode"] = ("Run for a duration", "Chạy trong một khoảng thời gian"), ["RepeatUntilTimeMode"] = ("Stop at a clock time", "Dừng vào giờ đã đặt"),
        ["DurationMinutes"] = ("DURATION (MINUTES)", "THỜI LƯỢNG (PHÚT)"), ["StopAtTime"] = ("STOP AT (HH:mm)", "DỪNG LÚC (HH:mm)"), ["InfiniteHelp"] = ("Runs continuously until you press Stop or the global hotkey.", "Chạy liên tục đến khi bạn nhấn Dừng hoặc phím tắt toàn cục."),
        ["Project"] = ("Project", "Dự án"), ["ModifiedHelp"] = ("An asterisk marks changes that have not been saved.", "Dấu hoa thị đánh dấu thay đổi chưa được lưu."),
        ["Workflow"] = ("Workflow", "Quy trình"), ["WorkflowHelp"] = ("Drag steps to reorder, or edit the same workflow as script.", "Kéo để đổi thứ tự, hoặc sửa cùng quy trình bằng mã lệnh."), ["AddAction"] = ("Add action", "Thêm thao tác"), ["VisualEditor"] = ("Visual editor", "Trình sửa trực quan"), ["ScriptEditor"] = ("Script editor", "Trình sửa mã lệnh"),
        ["NoActions"] = ("No actions yet", "Chưa có thao tác"), ["NoActionsHelp"] = ("Select a target, then Record - or use Add action to build the workflow manually.", "Chọn cửa sổ đích, sau đó Ghi - hoặc dùng Thêm thao tác để tạo thủ công."), ["Edit"] = ("Edit", "Sửa"), ["Duplicate"] = ("Duplicate", "Nhân bản"), ["Delete"] = ("Delete", "Xóa"), ["ClearAll"] = ("Clear all", "Xóa tất cả"), ["Current"] = ("CURRENT", "HIỆN TẠI"),
        ["ScriptHelp"] = ("Commands: CLICK, RIGHT_CLICK, DOUBLE_CLICK, DRAG, SCROLL, MOVE, TYPE, KEY, HOLD, WAIT, CALL. Add # NOTE before a step.", "Lệnh: CLICK, RIGHT_CLICK, DOUBLE_CLICK, DRAG, SCROLL, MOVE, TYPE, KEY, HOLD, WAIT, CALL. Thêm # NOTE trước một bước."),
        ["BackgroundMode"] = ("Playback engine", "Engine phát lại"), ["EngineActive"] = ("Engine", "Engine"),
        ["Click"] = ("Click", "Nhấp trái"), ["RightClick"] = ("Right click", "Nhấp phải"), ["DoubleClick"] = ("Double click", "Nhấp đúp"), ["Drag"] = ("Drag", "Kéo chuột"), ["Scroll"] = ("Mouse scroll", "Cuộn chuột"), ["MovePointer"] = ("Move pointer", "Di chuyển con trỏ"), ["TypeText"] = ("Type text", "Nhập văn bản"), ["KeyPress"] = ("Key press", "Nhấn phím"), ["KeyHold"] = ("Hold key", "Giữ phím"), ["Wait"] = ("Wait", "Chờ"), ["CallFunction"] = ("Call function", "Gọi hàm"),
        ["FunctionsTitle"] = ("Reusable functions", "Hàm dùng lại"), ["FunctionsHelp"] = ("Name a sequence once, then insert it anywhere with CALL.", "Đặt tên cho một chuỗi thao tác rồi chèn lại ở mọi nơi bằng CALL."), ["NewFunction"] = ("New function", "Hàm mới"), ["NoFunctions"] = ("No reusable functions", "Chưa có hàm dùng lại"), ["NoFunctionsHelp"] = ("Create a focused sequence for steps you use more than once.", "Tạo một chuỗi ngắn cho các bước bạn cần dùng nhiều lần."), ["FunctionEditorTitle"] = ("Edit reusable function", "Sửa hàm dùng lại"), ["FunctionEditorHelp"] = ("Write this function with the same concise commands as the main workflow.", "Viết hàm bằng cùng hệ lệnh ngắn gọn như quy trình chính."), ["FunctionName"] = ("FUNCTION NAME", "TÊN HÀM"), ["FunctionSteps"] = ("FUNCTION STEPS", "CÁC BƯỚC TRONG HÀM"), ["SaveFunction"] = ("Save function", "Lưu hàm"), ["ApplyFunctions"] = ("Apply changes", "Áp dụng thay đổi"), ["StepsLabel"] = ("steps", "bước"), ["FunctionToCall"] = ("Function to call", "Hàm cần gọi"), ["CallFunctionHelp"] = ("The called steps run here in order. Nested calls are supported; circular calls are blocked.", "Các bước trong hàm chạy lần lượt tại đây. Có thể gọi hàm lồng nhau; vòng gọi lặp sẽ bị chặn."),
        ["ScreenOverlay"] = ("Screen grid", "Lưới trên màn hình"), ["ScreenOverlayHelp"] = ("Switch to the target window to see its 25-pixel client grid, current points, and the X | Y label above your pointer. The overlay never accepts input.", "Chuyển sang cửa sổ đích để xem lưới vùng khách 25 pixel, các điểm hiện có và nhãn X | Y phía trên con trỏ. Overlay không nhận thao tác."), ["ShowGrid"] = ("Grid lines", "Đường lưới"), ["MarkerColor"] = ("Marker color", "Màu điểm"), ["MarkerShape"] = ("Marker icon", "Biểu tượng điểm"), ["MarkerBlue"] = ("Blue", "Xanh dương"), ["MarkerRed"] = ("Red", "Đỏ"), ["MarkerGreen"] = ("Green", "Xanh lá"), ["MarkerAmber"] = ("Amber", "Hổ phách"), ["MarkerPurple"] = ("Purple", "Tím"), ["MarkerPin"] = ("Pin", "Ghim"), ["MarkerDiamond"] = ("Diamond", "Kim cương"), ["MarkerCrosshair"] = ("Crosshair", "Tâm ngắm"),
        ["SettingsTitle"] = ("Settings", "Cài đặt"), ["Language"] = ("Language", "Ngôn ngữ"), ["English"] = ("English", "Tiếng Anh"), ["Vietnamese"] = ("Vietnamese", "Tiếng Việt"), ["GlobalHotkeys"] = ("Global hotkeys", "Phím tắt toàn cục"), ["RunHotkey"] = ("Run / emergency stop", "Chạy / dừng khẩn cấp"), ["PauseHotkey"] = ("Pause / resume", "Tạm dừng / tiếp tục"), ["PressShortcut"] = ("Click a field, then press a shortcut. Run/Stop always cancels held game input safely.", "Nhấp vào ô rồi nhấn tổ hợp phím. Chạy/Dừng luôn nhả input game đang giữ một cách an toàn."), ["SaveSettings"] = ("Save settings", "Lưu cài đặt"), ["Cancel"] = ("Cancel", "Hủy"), ["InputMode"] = ("Playback engine", "Engine phát lại"),
        ["Compatibility"] = ("Foreground playback can use the physical pointer. Background playback never activates the target, but software that accepts only raw input may ignore it. No mode bypasses security or service rules.", "Phát phía trước có thể dùng con trỏ vật lý. Phát nền không kích hoạt cửa sổ đích, nhưng phần mềm chỉ nhận raw input có thể bỏ qua. Không chế độ nào vượt cơ chế bảo vệ hoặc quy định dịch vụ."),
        ["PlaybackModeHelp"] = ("Choose the engine that matches how the target receives input and whether your own focus must remain untouched.", "Chọn engine theo cách cửa sổ đích nhận input và yêu cầu giữ nguyên focus bạn đang dùng."),
        ["AutomaticMode"] = ("1 — Strict background", "1 — Nền nghiêm ngặt"), ["AutomaticModeName"] = ("Strict background", "Nền nghiêm ngặt"), ["AutomaticModeHelp"] = ("Best for standard controls. Sends semantic or Win32 input without activating the target. Games that require raw input usually ignore this mode.", "Phù hợp với điều khiển tiêu chuẩn. Gửi input ngữ nghĩa hoặc Win32 mà không kích hoạt cửa sổ đích. Game yêu cầu raw input thường bỏ qua chế độ này."),
        ["GameForegroundMode"] = ("2 — Foreground input", "2 — Input phía trước"), ["GameForegroundModeName"] = ("Foreground input", "Input phía trước"), ["GameForegroundModeHelp"] = ("Most reliable for raw-input games. Run activates the selected target once, then uses the physical pointer and normal Windows input stream.", "Tin cậy nhất với game dùng raw input. Chạy sẽ kích hoạt cửa sổ đích một lần, sau đó dùng con trỏ vật lý và luồng input Windows thông thường."),
        ["GameBackgroundMode"] = ("3 — Background Engine v2 - experimental", "3 — Engine chạy nền v2 - thử nghiệm"), ["GameBackgroundModeName"] = ("Background Engine v2", "Engine chạy nền v2"), ["GameBackgroundModeHelp"] = ("Targets child controls and sends synthetic focus messages without activation. Delivery can be queued, but raw-input software may ignore it and processing cannot be verified.", "Nhắm tới control con và gửi thông điệp focus giả mà không kích hoạt. Input có thể được xếp gửi nhưng phần mềm raw input vẫn có thể bỏ qua và app không thể xác minh đã xử lý."),
        ["UiAutomationMode"] = ("4 — Modern controls (may take focus)", "4 — Điều khiển hiện đại (có thể lấy focus)"), ["UiAutomationModeName"] = ("Modern controls", "Điều khiển hiện đại"), ["UiAutomationModeHelp"] = ("Compatibility mode for custom modern controls. It may activate the target and interrupt typing.", "Chế độ tương thích cho điều khiển hiện đại tùy biến. Có thể kích hoạt cửa sổ đích và làm gián đoạn việc gõ."),
        ["Win32Mode"] = ("5 — Classic Win32 messages", "5 — Thông điệp Win32 cổ điển"), ["Win32ModeName"] = ("Classic Win32 messages", "Thông điệp Win32 cổ điển"), ["Win32ModeHelp"] = ("Sends direct window messages to legacy controls while leaving your pointer and focus free. Raw-input games usually ignore these messages.", "Gửi thông điệp cửa sổ trực tiếp tới điều khiển cũ, đồng thời giữ con trỏ và focus của bạn tự do. Game dùng raw input thường bỏ qua các thông điệp này."),
        ["ClientPoint"] = ("Client point", "Điểm vùng khách"), ["XCoordinate"] = ("X coordinate", "Tọa độ X"), ["YCoordinate"] = ("Y coordinate", "Tọa độ Y"), ["PickNewPoint"] = ("Pick new point", "Chọn điểm mới"), ["TestPoint"] = ("Test point", "Kiểm tra điểm"), ["CoordinateHelp"] = ("Coordinates are relative to the target's client area, not the screen.", "Tọa độ tính theo vùng khách của cửa sổ đích, không phải màn hình."),
        ["TextToType"] = ("Text to type", "Văn bản cần nhập"), ["KeyOrShortcut"] = ("Key or shortcut", "Phím hoặc tổ hợp phím"), ["ShortcutHelp"] = ("Shortcuts such as CTRL+C and ALT+F4 are also accepted.", "Cũng chấp nhận tổ hợp như CTRL+C và ALT+F4."), ["HoldDuration"] = ("Duration (milliseconds)", "Thời lượng (mili giây)"), ["HoldHelp"] = ("Held input is released when paused, stopped, or when a foreground game loses focus.", "Input đang giữ sẽ được nhả khi tạm dừng, dừng hoặc khi game phía trước mất focus."), ["StartX"] = ("Start X", "X bắt đầu"), ["StartY"] = ("Start Y", "Y bắt đầu"), ["EndX"] = ("End X", "X kết thúc"), ["EndY"] = ("End Y", "Y kết thúc"), ["DragHelp"] = ("Game foreground mode moves the physical pointer along this client-relative path.", "Chế độ game phía trước di chuyển con trỏ thật theo đường đi tương đối với vùng khách này."), ["WaitDuration"] = ("Wait duration", "Thời gian chờ"), ["Milliseconds"] = ("Milliseconds", "Mili giây"), ["MillisecondHelp"] = ("1000 milliseconds equals one second.", "1000 mili giây bằng một giây."),
        ["WheelDelta"] = ("Wheel delta", "Độ cuộn bánh xe"), ["ScrollHelp"] = ("Positive scrolls up, negative scrolls down. One wheel notch is 120.", "Số dương cuộn lên, số âm cuộn xuống. Một nấc bánh xe là 120."),
        ["EditActionHelp"] = ("Edit the action, then save it back to the workflow.", "Sửa thao tác rồi lưu lại vào quy trình."), ["DelayBefore"] = ("Delay before this action (ms)", "Độ trễ trước thao tác (ms)"), ["ActionEnabled"] = ("Action enabled", "Bật thao tác"), ["ActionNote"] = ("Optional note", "Ghi chú tùy chọn"), ["ActionNoteHelp"] = ("Shown inline in the workflow and preserved in project files and DSL.", "Hiển thị ngay trong quy trình và được giữ trong tệp dự án lẫn DSL."), ["SaveAction"] = ("Save action", "Lưu thao tác"),
        ["Add"] = ("Add", "Thêm"), ["OpenProjectDialog"] = ("Open automation project", "Mở dự án tự động hóa"), ["SaveProjectDialog"] = ("Save automation project", "Lưu dự án tự động hóa"),
        ["Ready"] = ("Ready - Select a target window to begin", "Sẵn sàng - Chọn cửa sổ đích để bắt đầu"), ["NoTarget"] = ("No target selected", "Chưa chọn cửa sổ đích")
    };

    public static string Get(string key) => Text.TryGetValue(key, out var value) ? (_language == "vi" ? value.Vi : value.En) : key;

    public static void Apply(string language)
    {
        _language = language.Equals("vi", StringComparison.OrdinalIgnoreCase) ? "vi" : "en";
        if (Application.Current is { } app) foreach (var item in Text) app.Resources[item.Key] = _language == "vi" ? item.Value.Vi : item.Value.En;
        LanguageChanged?.Invoke(null, EventArgs.Empty);
    }
}
