using System.Windows;

namespace BackgroundAutomationStudio.Services;

public static class LocalizationService
{
    private static string _language = "en";
    public static string Language => _language;
    public static event EventHandler? LanguageChanged;

    private static readonly Dictionary<string, (string En, string Vi)> Text = new()
    {
        ["MenuFile"] = ("File", "Tệp"), ["MenuEdit"] = ("Edit", "Chỉnh sửa"), ["MenuHotkey"] = ("Hotkey", "Phím tắt"), ["MenuSettings"] = ("Settings", "Cài đặt"), ["RunStopShort"] = ("Run/Stop", "Chạy/Dừng"), ["PauseShort"] = ("Pause", "Tạm dừng"),
        ["NewProject"] = ("New project", "Dự án mới"), ["Open"] = ("Open...", "Mở..."), ["Save"] = ("Save", "Lưu"), ["SaveAs"] = ("Save as...", "Lưu thành..."),
        ["EditAction"] = ("Edit action", "Sửa thao tác"), ["DuplicateAction"] = ("Duplicate action", "Nhân bản thao tác"), ["DeleteAction"] = ("Delete action", "Xóa thao tác"), ["Undo"] = ("Undo", "Hoàn tác"), ["Redo"] = ("Redo", "Làm lại"), ["MoveUp"] = ("Move up", "Di chuyển lên"), ["MoveDown"] = ("Move down", "Di chuyển xuống"),
        ["VersionLabel"] = ("Version 1.5 - Game Macro & Focus Guard", "Phiên bản 1.5 - Macro game & Bảo vệ focus"),
        ["TargetWindow"] = ("Target window", "Cửa sổ đích"), ["ClientCoordinates"] = ("CLIENT COORDINATES", "TỌA ĐỘ VÙNG KHÁCH"), ["TargetHelp"] = ("Choose the exact window that receives recorded and replayed actions.", "Chọn đúng cửa sổ sẽ nhận thao tác ghi và phát lại."), ["SelectWindow"] = ("Select window", "Chọn cửa sổ"),
        ["Application"] = ("APPLICATION", "ỨNG DỤNG"), ["WindowTitle"] = ("WINDOW TITLE", "TIÊU ĐỀ CỬA SỔ"), ["Class"] = ("CLASS", "LỚP"), ["NotSelected"] = ("Not selected", "Chưa chọn"), ["NotCaptured"] = ("Not captured", "Chưa ghi nhận"), ["RecordedLayout"] = ("RECORDED WINDOW LAYOUT", "BỐ CỤC CỬA SỔ ĐÃ GHI"),
        ["CapturePlayback"] = ("Capture & playback", "Ghi & phát lại"), ["Recording"] = ("RECORDING", "ĐANG GHI"), ["Record"] = ("Record", "Ghi"), ["StopRecord"] = ("Stop record", "Dừng ghi"), ["CancelRecord"] = ("Cancel record", "Hủy ghi"), ["RunWorkflow"] = ("Run workflow", "Chạy quy trình"), ["Pause"] = ("Pause", "Tạm dừng"), ["Resume"] = ("Resume", "Tiếp tục"), ["StopRun"] = ("Stop run", "Dừng chạy"),
        ["RepeatMode"] = ("RUN SCHEDULE", "LỊCH CHẠY"), ["RepeatCount"] = ("REPEAT COUNT", "SỐ LẦN LẶP"), ["RepeatHelp"] = ("Choose a count, run forever, run for a duration, or stop at a clock time.", "Chọn số lần, chạy vô tận, chạy theo thời lượng hoặc dừng tại một giờ cụ thể."),
        ["RepeatCountMode"] = ("Repeat a set number", "Lặp theo số lần"), ["RepeatInfiniteMode"] = ("Run until stopped", "Chạy vô tận đến khi dừng"), ["RepeatDurationMode"] = ("Run for a duration", "Chạy trong một khoảng thời gian"), ["RepeatUntilTimeMode"] = ("Stop at a clock time", "Dừng vào giờ đã đặt"),
        ["DurationMinutes"] = ("DURATION (MINUTES)", "THỜI LƯỢNG (PHÚT)"), ["StopAtTime"] = ("STOP AT (HH:mm)", "DỪNG LÚC (HH:mm)"), ["InfiniteHelp"] = ("Runs continuously until you press Stop or the global hotkey.", "Chạy liên tục đến khi bạn nhấn Dừng hoặc phím tắt toàn cục."),
        ["Project"] = ("Project", "Dự án"), ["ModifiedHelp"] = ("An asterisk marks changes that have not been saved.", "Dấu hoa thị đánh dấu thay đổi chưa được lưu."),
        ["Workflow"] = ("Workflow", "Quy trình"), ["WorkflowHelp"] = ("Drag steps to reorder, or edit the same workflow as script.", "Kéo để đổi thứ tự, hoặc sửa cùng quy trình bằng mã lệnh."), ["AddAction"] = ("Add action", "Thêm thao tác"), ["VisualEditor"] = ("Visual editor", "Trình sửa trực quan"), ["ScriptEditor"] = ("Script editor", "Trình sửa mã lệnh"),
        ["NoActions"] = ("No actions yet", "Chưa có thao tác"), ["NoActionsHelp"] = ("Select a target, then Record - or use Add action to build the workflow manually.", "Chọn cửa sổ đích, sau đó Ghi - hoặc dùng Thêm thao tác để tạo thủ công."), ["Edit"] = ("Edit", "Sửa"), ["Duplicate"] = ("Duplicate", "Nhân bản"), ["Delete"] = ("Delete", "Xóa"), ["ClearAll"] = ("Clear all", "Xóa tất cả"), ["Current"] = ("CURRENT", "HIỆN TẠI"),
        ["ScriptHelp"] = ("Commands: CLICK, RIGHT_CLICK, DOUBLE_CLICK, DRAG, TYPE, KEY, HOLD, WAIT. Valid edits update the visual workflow immediately.", "Lệnh: CLICK, RIGHT_CLICK, DOUBLE_CLICK, DRAG, TYPE, KEY, HOLD, WAIT. Mã hợp lệ cập nhật quy trình trực quan ngay lập tức."),
        ["BackgroundMode"] = ("Local playback - engine selected in Settings", "Phát cục bộ - chọn engine trong Cài đặt"),
        ["Click"] = ("Click", "Nhấp trái"), ["RightClick"] = ("Right click", "Nhấp phải"), ["DoubleClick"] = ("Double click", "Nhấp đúp"), ["Drag"] = ("Drag", "Kéo chuột"), ["TypeText"] = ("Type text", "Nhập văn bản"), ["KeyPress"] = ("Key press", "Nhấn phím"), ["KeyHold"] = ("Hold key", "Giữ phím"), ["Wait"] = ("Wait", "Chờ"),
        ["SettingsTitle"] = ("Settings", "Cài đặt"), ["Language"] = ("Language", "Ngôn ngữ"), ["English"] = ("English", "Tiếng Anh"), ["Vietnamese"] = ("Vietnamese", "Tiếng Việt"), ["GlobalHotkeys"] = ("Global hotkeys", "Phím tắt toàn cục"), ["RunHotkey"] = ("Run / emergency stop", "Chạy / dừng khẩn cấp"), ["PauseHotkey"] = ("Pause / resume", "Tạm dừng / tiếp tục"), ["PressShortcut"] = ("Click a field, then press a shortcut. Run/Stop always cancels held game input safely.", "Nhấp vào ô rồi nhấn tổ hợp phím. Chạy/Dừng luôn nhả input game đang giữ một cách an toàn."), ["SaveSettings"] = ("Save settings", "Lưu cài đặt"), ["Cancel"] = ("Cancel", "Hủy"), ["InputMode"] = ("Playback engine", "Engine phát lại"),
        ["Compatibility"] = ("Game foreground mode uses the normal Windows input stream and may move the physical pointer. Experimental background mode never activates the game, but many games ignore it. Neither mode bypasses anti-cheat or server rules.", "Chế độ game phía trước dùng luồng input Windows thông thường và có thể di chuyển con trỏ thật. Chế độ nền thử nghiệm không kích hoạt game nhưng nhiều game sẽ bỏ qua. Không chế độ nào vượt anti-cheat hoặc quy định máy chủ."),
        ["PlaybackModeHelp"] = ("Desktop modes preserve your current input. Game modes trade background guarantees for game compatibility.", "Chế độ desktop giữ nguyên input bạn đang dùng. Chế độ game đánh đổi khả năng chạy nền để tăng tương thích với game."),
        ["AutomaticMode"] = ("Strict background (recommended)", "Nền nghiêm ngặt (khuyên dùng)"), ["AutomaticModeHelp"] = ("Use focus-safe semantic commands, then Win32 messages. Never invoke focus-taking UI Automation.", "Dùng lệnh ngữ nghĩa giữ focus, sau đó dùng thông điệp Win32. Không gọi UI Automation có thể cướp focus."),
        ["UiAutomationMode"] = ("Modern controls (may take focus)", "Điều khiển hiện đại (có thể lấy focus)"), ["UiAutomationModeHelp"] = ("Explicit compatibility mode for unsupported modern controls. The target may interrupt typing or IME composition.", "Chế độ tương thích chủ động cho điều khiển hiện đại chưa hỗ trợ. Cửa sổ đích có thể làm gián đoạn gõ hoặc bộ gõ IME."),
        ["Win32Mode"] = ("Classic Win32 messages", "Thông điệp Win32 cổ điển"), ["Win32ModeHelp"] = ("Send pointer clicks directly as window messages for classic desktop applications.", "Gửi lần nhấp trực tiếp dưới dạng thông điệp cửa sổ cho ứng dụng desktop cổ điển."),
        ["GameForegroundMode"] = ("Game macro - foreground (recommended for games)", "Macro game - phía trước (khuyên dùng cho game)"), ["GameForegroundModeHelp"] = ("Uses real Windows input for compatibility. If you switch apps, the macro releases held input and auto-pauses instead of taking focus back.", "Dùng input Windows thật để tương thích. Khi bạn chuyển app, macro nhả input đang giữ và tự tạm dừng thay vì giành lại focus."),
        ["GameBackgroundMode"] = ("Game background - experimental", "Game chạy nền - thử nghiệm"), ["GameBackgroundModeHelp"] = ("Sends targeted window messages without moving the pointer or activating the game. Project Zomboid and other raw-input games may ignore every action.", "Gửi thông điệp nhắm đích mà không di chuyển con trỏ hoặc kích hoạt game. Project Zomboid và game raw-input khác có thể bỏ qua toàn bộ thao tác."),
        ["ClientPoint"] = ("Client point", "Điểm vùng khách"), ["XCoordinate"] = ("X coordinate", "Tọa độ X"), ["YCoordinate"] = ("Y coordinate", "Tọa độ Y"), ["PickNewPoint"] = ("Pick new point", "Chọn điểm mới"), ["TestPoint"] = ("Test point", "Kiểm tra điểm"), ["CoordinateHelp"] = ("Coordinates are relative to the target's client area, not the screen.", "Tọa độ tính theo vùng khách của cửa sổ đích, không phải màn hình."),
        ["TextToType"] = ("Text to type", "Văn bản cần nhập"), ["KeyOrShortcut"] = ("Key or shortcut", "Phím hoặc tổ hợp phím"), ["ShortcutHelp"] = ("Shortcuts such as CTRL+C and ALT+F4 are also accepted.", "Cũng chấp nhận tổ hợp như CTRL+C và ALT+F4."), ["HoldDuration"] = ("Duration (milliseconds)", "Thời lượng (mili giây)"), ["HoldHelp"] = ("Held input is released when paused, stopped, or when a foreground game loses focus.", "Input đang giữ sẽ được nhả khi tạm dừng, dừng hoặc khi game phía trước mất focus."), ["StartX"] = ("Start X", "X bắt đầu"), ["StartY"] = ("Start Y", "Y bắt đầu"), ["EndX"] = ("End X", "X kết thúc"), ["EndY"] = ("End Y", "Y kết thúc"), ["DragHelp"] = ("Game foreground mode moves the physical pointer along this client-relative path.", "Chế độ game phía trước di chuyển con trỏ thật theo đường đi tương đối với vùng khách này."), ["WaitDuration"] = ("Wait duration", "Thời gian chờ"), ["Milliseconds"] = ("Milliseconds", "Mili giây"), ["MillisecondHelp"] = ("1000 milliseconds equals one second.", "1000 mili giây bằng một giây."),
        ["EditActionHelp"] = ("Edit the action, then save it back to the workflow.", "Sửa thao tác rồi lưu lại vào quy trình."), ["DelayBefore"] = ("Delay before this action (ms)", "Độ trễ trước thao tác (ms)"), ["ActionEnabled"] = ("Action enabled", "Bật thao tác"), ["SaveAction"] = ("Save action", "Lưu thao tác"),
        ["Add"] = ("Add", "Thêm"), ["OpenProjectDialog"] = ("Open automation project", "Mở dự án tự động hóa"), ["SaveProjectDialog"] = ("Save automation project", "Lưu dự án tự động hóa"),
        ["Ready"] = ("Ready - Select a target window to begin", "Sẵn sàng - Chọn cửa sổ đích để bắt đầu"), ["NoTarget"] = ("No target selected", "Chưa chọn cửa sổ đích")
    };

    public static string Get(string key) => Text.TryGetValue(key, out var value) ? (_language == "vi" ? value.Vi : value.En) : key;

    public static void Apply(string language)
    {
        _language = language.Equals("vi", StringComparison.OrdinalIgnoreCase) ? "vi" : "en";
        if (Application.Current is { } app) foreach (var item in Text) app.Resources[item.Key] = _language == "vi" ? item.Value.Vi : item.Value.En;
        LanguageChanged?.Invoke(null, EventArgs.Empty);
    }
}
